Development
portatlas/tictactoe-clojure pull request #1
Opened 2017-02-25 00:02 UTC by portatlas

2017-02-27 05:17 UTC, jayden requested changes

2017-02-27 05:17 UTC, jayden commented on spec/tictactoe_clojure/board_spec.clj
> +			(should= new-board [0 1 2 3 4 5 6 7 8] )))
`[0 1 2 3 4 5 6 7 8]` seems to be repeated a few times here. We could pull this out and refer to it. Similar comment about the "X" and "O"'s

2017-02-27 05:17 UTC, jayden commented on spec/tictactoe_clojure/board_spec.clj
> +			(should= nil (valid-move? [1 2 3 4 5 6 7 8] 0 )))
Why does this return `nil` if it's invalid?

2017-02-27 05:17 UTC, jayden commented on src/tictactoe_clojure/board.clj
> +(defn valid-move?
Should the responsibility of validating a move be placed on the Board?

2017-02-27 05:17 UTC, jayden commented on src/tictactoe_clojure/board.clj
> +	[current-turn]
Similar question here about the board's responsibility and whether or not it should know whose turn it is.

2017-02-27 05:17 UTC, jayden commented on src/tictactoe_clojure/io.clj
> +(ns tictactoe-clojure.io)
The name `io` is a bit too general for this namespace. It is a type of IO, but it's console specific. It might be a good idea to rename this.

2017-02-27 05:17 UTC, jayden commented on spec/tictactoe_clojure/io_spec.clj
> +  )
Missing newline here. Looks like all of your other files have a newline, so let's make sure we keep this consistent. I'd also suggest moving this closing paren up a line.

2017-02-27 05:17 UTC, jayden commented on src/tictactoe_clojure/board.clj
> +
Extra newline here

2017-02-27 05:17 UTC, jayden commented on spec/tictactoe_clojure/board_spec.clj
> +
Extra newlines here

2017-02-27 06:02 UTC, tbaik commented on spec/tictactoe_clojure/io_spec.clj
> +  			(with-out-str "1"
We talked about this when pairing - Let's remove the "1"

2017-02-27 06:02 UTC, tbaik commented on spec/tictactoe_clojure/rules_spec.clj
> +
Let's leave things that are not part of this PR (Creating the Board) out of the commit

2017-02-27 06:02 UTC, tbaik commented on src/tictactoe_clojure/board.clj
> +	(filter integer? board))
Nice use of filter here 👍

2017-02-27 06:02 UTC, tbaik commented on src/tictactoe_clojure/board.clj
> +	(if (= current-turn "X") "O" "X"))
Why is this here?

1. Is this the responsibility of the board? Why is the board deciding whose turn it is?
2. How do you know you need this function? I think I understand the use for #valid-slots, #valid-move? and #move, but not this. I'm guessing that you're copying this over from your ruby board. However, I would recommend that you don't look at how you implemented your ruby version and design your clojure TTT in a way that best fits your new understanding of the SOLID principles

2017-02-28 17:39 UTC, portatlas commented on spec/tictactoe_clojure/board_spec.clj
> +			(should= nil (valid-move? [1 2 3 4 5 6 7 8] 0 )))
`valid-move?` uses the `[some](https://clojuredocs.org/clojure.core/some)` function to determine if the user input is present in the collection of the valid slots. `some` returns nil if the predicate value is not in the collection.

2017-02-28 23:54 UTC, closed without merging